---
name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  id-token: write
  checks: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      project-name: Sdk
      project-path: ./src/Sdk

